### ISSUE TITLE
Modifying components is invalid && report an error

### ISSUE THREAD

**Issue by WindChim1** [CloudPSS/docs#16]
![1727235502736](https://github.com/user-attachments/assets/d2a46862-b44e-4b18-b152-a9bbdd5970bf)

According to the print log, after modifying some parameters of the component, nothing actually changes, and when the label is modified, an error is reported.

**Comment by OpportunityLiu** [comment]
Fixed in `cloudpss-4.5.3`.
Please run `pip install -U cloudpss` to upgrade to the latest version.
